name: CI
on: [push]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: aarch64-linux-android
          components: rust-src

      - name: Setup NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27

      - name: Add NDK Toolchain to path
        run: |
          echo "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/" >> $GITHUB_PATH
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Build Module
        run: |
          make

      - name: Upload Module Artifact
        uses: actions/upload-artifact@v4
        with:
          name: module
          path: "module/ZygiskHide.zip"
